 Python資料分析之pandas統計分析  
 參考網站 https://www.796t.com/content/1547751817.html

掛接雲端硬碟

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

設定自己設定的子資料夾:MyPyProj路徑

In [2]:
folder="/content/drive/MyDrive/資料科學自學聖經/ch02/"

輸入numpy套件,並更名為np  
輸入pandas套件,並更名為pd

In [7]:
import numpy as np
import pandas as pd

隨機生成三組資料

In [8]:
np.random.seed(1234)
d1 = pd.Series(2*np.random.normal(size = 100)+3)
d2 = np.random.f(2,4,size = 100)
d3 = np.random.randint(1,100,size = 100)

統計分析用到的函式

In [5]:
d1.count()          #非空元素計算
d1.min()           #最小值
d1.max()           #最大值
d1.idxmin()          #最小值的位置，類似於R中的which.min函式
d1.idxmax()          #最大值的位置，類似於R中的which.max函式
d1.quantile(0.1)       #10%分位數
d1.sum()           #求和
d1.mean()           #均值
d1.median()          #中位數
d1.mode()           #眾數
d1.var()           #方差
d1.std()           #標準差
#d1.mad()           #平均絕對偏差

d1.skew()           #偏度
d1.kurt()           #峰度
d1.describe()         #一次性輸出多個描述性統計指標

count    100.000000
mean       3.070225
std        2.001402
min       -4.127033
25%        2.040101
50%        3.204555
75%        4.434788
max        7.781921
dtype: float64

In [9]:
d1.count()          #非空元素計算
d1.min()           #最小值
d1.max()           #最大值
d1.idxmin()          #最小值的位置，類似於R中的which.min函式
d1.idxmax()          #最大值的位置，類似於R中的which.max函式
d1.quantile(0.1)       #10%分位數
d1.sum()           #求和
d1.mean()           #均值
d1.median()          #中位數
d1.mode()           #眾數
d1.var()           #方差
d1.std()           #標準差
#d1.mad()           #平均絕對偏差
d1.skew()           #偏度
d1.kurt()           #峰度
d1.describe()         #一次性輸出多個描述性統計指標

count    100.000000
mean       3.070225
std        2.001402
min       -4.127033
25%        2.040101
50%        3.204555
75%        4.434788
max        7.781921
dtype: float64

※ 必須注意的是，descirbe方法只能針對序列或資料框，一維陣列是沒有這個方法的

自定義一個函式，將這些統計指標彙總在一起：

In [10]:
def status(x) :
    return pd.Series([x.count(),x.min(),x.idxmin(),x.quantile(.25),x.median(),
                      x.quantile(.75),x.mean(),x.max(),x.idxmax(),x.mad(),x.var(),
                      x.std(),x.skew(),x.kurt()],index=['總數','最小值','最小值位置','25%分位數',
                    '中位數','75%分位數','均值','最大值','最大值位數','平均絕對偏差','方差','標準差','偏度','峰度'])

執行該函式，檢視一下d1資料集的這些統計函式值：

In [11]:
df = pd.DataFrame(status(d1))
df

<ipython-input-10-9e22ac0a7fd4>:3: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  x.quantile(.75),x.mean(),x.max(),x.idxmax(),x.mad(),x.var(),

                 0
總數      100.000000
最小值      -4.127033
最小值位置    81.000000
25%分位數    2.040101
中位數       3.204555
75%分位數    4.434788
均值        3.070225
最大值       7.781921
最大值位數    39.000000
平均絕對偏差    1.511288
方差        4.005609
標準差       2.001402
偏度       -0.649478
峰度        1.220109

需要處理的是一系列的數值型資料框，如何將這個函式應用到資料框中的每一列呢？可以使用apply函式，這個非常類似於R中的apply的應用方法。

In [12]:
df = pd.DataFrame(np.array([d1,d2,d3]).T, columns=['x1','x2','x3'])
df.head()

df.apply(status)

<ipython-input-10-9e22ac0a7fd4>:3: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  x.quantile(.75),x.mean(),x.max(),x.idxmax(),x.mad(),x.var(),
<ipython-input-10-9e22ac0a7fd4>:3: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  x.quantile(.75),x.mean(),x.max(),x.idxmax(),x.mad(),x.var(),
<ipython-input-10-9e22ac0a7fd4>:3: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  x.quantile(.75),x.mean(),x.max(),x.idxmax(),x.mad(),x.var(),

                x1          x2          x3
總數      100.000000  100.000000  100.000000
最小值      -4.127033    0.014330    3.000000
最小值位置    81.000000   72.000000   76.000000
25%分位數    2.040101    0.249580   25.000000
中位數       3.204555    1.000613   54.500000
75%分位數    4.434788    2.101581   73.000000
均值        3.070225    2.028608   51.490000
最大值       7.781921   18.791565   98.000000
最大值位數    39.000000   53.000000   96.000000
平均絕對偏差    1.511288    1.922669   24.010800
方差        4.005609   10.206447  780.090808
標準差       2.001402    3.194753   27.930106
偏度       -0.649478    3.326246   -0.118917
峰度        1.220109   12.636286   -1.211579

載入CSV資料

In [13]:
import numpy as np
import pandas as pd

qust = pd.read_csv("/content/drive/MyDrive/MyMLProj/Questionnaire.csv")
qust.head()    #檢視前5行

,N0.,A1,A2,A3,A4,A5,B1,B2,B3,B4,...,C2,C3,C4,D1,D2,D3,D4,E1,E2,E3
0,1,1,1,2,2,1,2,2,1,2,...,2,1,3,2,1,3,2,2,2,1
1,2,1,1,2,2,1,2,2,1,2,...,2,3,1,2,1,3,2,2,2,1
2,3,1,2,2,2,1,2,2,1,2,...,2,3,1,2,1,3,2,2,2,1
3,4,1,2,2,2,1,2,2,1,2,...,2,4,3,2,1,3,2,2,2,1
4,5,1,1,2,2,1,2,2,1,2,...,2,1,1,2,1,3,2,2,2,1

描述性統計1：describe()

In [15]:
result = qust['D3'].describe()
pd.DataFrame(result )   #格式化成DataFrame

              D3
count  20.000000
mean    2.200000
std     1.105013
min     1.000000
25%     1.000000
50%     2.500000
75%     3.000000
max     4.000000

from matplotlib import pyplot as plt
_df_4['D3'].plot(kind='hist', bins=20, title='D3')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_5.groupby('index').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6['D3'].plot(kind='line', figsize=(8, 4), title='D3')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_7['index'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_7, x='D3', y='index', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

描述性統計2：describe(include=[‘number’])

include中填寫的是資料型別，若想檢視所有資料的統計資料，則可填寫object，即include=['object']；若想檢視float型別的資料，則為include=['float']。

In [ ]:
#result = qust.describe(include=['object'])
result = qust.describe(include=['number'])
pd.DataFrame(result)   #格式化成DataFrame

,N0.,A1,A2,A3,A4,A5,B1,B2,B3,B4,...,C2,C3,C4,D1,D2,D3,D4,E1,E2,E3
count,20.00000,20.000000,20.000000,20.0,20.0,20.0,20.000000,20.00000,20.000000,20.000000,...,20.000000,20.000000,20.000000,20.000000,20.0,20.000000,20.00000,20.000000,20.000000,20.0
mean,10.50000,1.300000,1.600000,2.0,2.0,1.0,1.550000,1.65000,1.100000,1.900000,...,1.950000,1.750000,1.700000,1.850000,1.0,2.200000,1.65000,1.750000,1.800000,1.0
std,5.91608,0.470162,0.502625,0.0,0.0,0.0,0.510418,0.48936,0.307794,0.307794,...,0.223607,0.966546,0.732695,0.366348,0.0,1.105013,0.48936,0.444262,0.410391,0.0
min,1.00000,1.000000,1.000000,2.0,2.0,1.0,1.000000,1.00000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.00000,1.000000,1.000000,1.0
25%,5.75000,1.000000,1.000000,2.0,2.0,1.0,1.000000,1.00000,1.000000,2.000000,...,2.000000,1.000000,1.000000,2.000000,1.0,1.000000,1.00000,1.750000,2.000000,1.0
50%,10.50000,1.000000,2.000000,2.0,2.0,1.0,2.000000,2.00000,1.000000,2.000000,...,2.000000,1.000000,2.000000,2.000000,1.0,2.500000,2.00000,2.000000,2.000000,1.0
75%,15.25000,2.000000,2.000000,2.0,2.0,1.0,2.000000,2.00000,1.000000,2.000000,...,2.000000,2.250000,2.000000,2.000000,1.0,3.000000,2.00000,2.000000,2.000000,1.0
max,20.00000,2.000000,2.000000,2.0,2.0,1.0,2.000000,2.00000,2.000000,2.000000,...,2.000000,4.000000,3.000000,2.000000,1.0,4.000000,2.00000,2.000000,2.000000,1.0

連續變數的相關係數（corr）

In [16]:
qust.corr()

,N0.,A1,A2,A3,A4,A5,B1,B2,B3,B4,...,C2,C3,C4,D1,D2,D3,D4,E1,E2,E3
N0.,1.000000,0.245985,1.238987e-01,NaN,NaN,NaN,-0.200440,-0.118167,0.144518,-0.144518,...,-0.338179,-4.372035e-01,0.012142,-0.303549,NaN,-0.080509,-0.118167,-1.301628e-01,-2.167775e-01,NaN
A1,0.245985,1.000000,5.345225e-01,NaN,NaN,NaN,0.153522,0.022875,-0.218218,0.218218,...,0.150188,-2.895451e-01,0.122226,-0.030557,NaN,0.081044,0.022875,1.259882e-01,5.455447e-02,NaN
A2,0.123899,0.534522,1.000000e+00,NaN,NaN,NaN,0.082061,0.042796,-0.068041,0.068041,...,0.280976,1.083378e-01,0.228665,-0.057166,NaN,-0.227429,0.042796,8.831770e-17,-1.530931e-01,NaN
A3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B1,-0.200440,0.153522,8.206099e-02,NaN,NaN,NaN,1.000000,0.811246,-0.368514,0.368514,...,-0.207514,1.866965e-01,0.182953,0.464420,NaN,0.167968,0.811246,6.382847e-01,5.527708e-01,NaN
B2,-0.118167,0.022875,4.279605e-02,NaN,NaN,NaN,0.811246,1.000000,0.244600,-0.244600,...,-0.168345,2.503673e-01,0.278900,0.572478,NaN,0.233594,1.000000,7.867958e-01,6.813851e-01,NaN
B3,0.144518,-0.218218,-6.804138e-02,NaN,NaN,NaN,-0.368514,0.244600,1.000000,-1.000000,...,0.076472,8.845748e-02,0.140028,0.140028,NaN,0.092848,0.244600,1.924501e-01,1.666667e-01,NaN
B4,-0.144518,0.218218,6.804138e-02,NaN,NaN,NaN,0.368514,-0.244600,-1.000000,1.000000,...,-0.076472,-8.845748e-02,-0.140028,-0.140028,NaN,-0.092848,-0.244600,-1.924501e-01,-1.666667e-01,NaN
C1,-0.414882,-0.118403,1.812366e-01,NaN,NaN,NaN,0.262747,0.305078,0.049326,-0.049326,...,-0.033949,6.937624e-01,0.006907,-0.062164,NaN,0.073277,0.305078,1.423929e-01,4.932636e-02,NaN
C2,-0.338179,0.150188,2.809757e-01,NaN,NaN,NaN,-0.207514,-0.168345,0.076472,-0.076472,...,1.000000,-6.088061e-02,-0.096374,-0.096374,NaN,0.255609,-0.168345,-1.324532e-01,-1.147079e-01,NaN
C3,-0.437203,-0.289545,1.083378e-01,NaN,NaN,NaN,0.186697,0.250367,0.088457,-0.088457,...,-0.060881,1.000000e+00,0.185798,0.185798,NaN,0.049278,0.250367,9.192771e-02,-9.575234e-17,NaN
C4,0.012142,0.122226,2.286648e-01,NaN,NaN,NaN,0.182953,0.278900,0.140028,-0.140028,...,-0.096374,1.857979e-01,1.000000,0.019608,NaN,0.273027,0.278900,8.084521e-02,-3.500700e-02,NaN
D1,-0.303549,-0.030557,-5.716620e-02,NaN,NaN,NaN,0.464420,0.572478,0.140028,-0.140028,...,-0.096374,1.857979e-01,0.019608,1.000000,NaN,-0.052005,0.572478,7.276069e-01,8.401681e-01,NaN
D2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
D3,-0.080509,0.081044,-2.274294e-01,NaN,NaN,NaN,0.167968,0.233594,0.092848,-0.092848,...,0.255609,4.927843e-02,0.273027,-0.052005,NaN,1.000000,0.233594,1.072113e-01,9.284767e-02,NaN
D4,-0.118167,0.022875,4.279605e-02,NaN,NaN,NaN,0.811246,1.000000,0.244600,-0.244600,...,-0.168345,2.503673e-01,0.278900,0.572478,NaN,0.233594,1.000000,7.867958e-01,6.813851e-01,NaN
E1,-0.130163,0.125988,8.831770e-17,NaN,NaN,NaN,0.638285,0.786796,0.192450,-0.192450,...,-0.132453,9.192771e-02,0.080845,0.727607,NaN,0.107211,0.786796,1.000000e+00,8.660254e-01,NaN
E2,-0.216777,0.054554,-1.530931e-01,NaN,NaN,NaN,0.552771,0.681385,0.166667,-0.166667,...,-0.114708,-9.575234e-17,-0.035007,0.840168,NaN,0.092848,0.681385,8.660254e-01,1.000000e+00,NaN
E3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

協方差矩陣（cov）

In [17]:
qust.cov()

,N0.,A1,A2,A3,A4,A5,B1,B2,B3,B4,...,C2,C3,C4,D1,D2,D3,D4,E1,E2,E3
N0.,35.000000,0.684211,0.368421,0.0,0.0,0.0,-0.605263,-0.342105,0.263158,-0.263158,...,-0.447368,-2.500000e+00,0.052632,-0.657895,0.0,-0.526316,-0.342105,-0.342105,-5.263158e-01,0.0
A1,0.684211,0.221053,0.126316,0.0,0.0,0.0,0.036842,0.005263,-0.031579,0.031579,...,0.015789,-1.315789e-01,0.042105,-0.005263,0.0,0.042105,0.005263,0.026316,1.052632e-02,0.0
A2,0.368421,0.126316,0.252632,0.0,0.0,0.0,0.021053,0.010526,-0.010526,0.010526,...,0.031579,5.263158e-02,0.084211,-0.010526,0.0,-0.126316,0.010526,0.000000,-3.157895e-02,0.0
A3,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000e+00,0.0
A4,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000e+00,0.0
A5,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000e+00,0.0
B1,-0.605263,0.036842,0.021053,0.0,0.0,0.0,0.260526,0.202632,-0.057895,0.057895,...,-0.023684,9.210526e-02,0.068421,0.086842,0.0,0.094737,0.202632,0.144737,1.157895e-01,0.0
B2,-0.342105,0.005263,0.010526,0.0,0.0,0.0,0.202632,0.239474,0.036842,-0.036842,...,-0.018421,1.184211e-01,0.100000,0.102632,0.0,0.126316,0.239474,0.171053,1.368421e-01,0.0
B3,0.263158,-0.031579,-0.010526,0.0,0.0,0.0,-0.057895,0.036842,0.094737,-0.094737,...,0.005263,2.631579e-02,0.031579,0.015789,0.0,0.031579,0.036842,0.026316,2.105263e-02,0.0
B4,-0.263158,0.031579,0.010526,0.0,0.0,0.0,0.057895,-0.036842,-0.094737,0.094737,...,-0.005263,-2.631579e-02,-0.031579,-0.015789,0.0,-0.031579,-0.036842,-0.026316,-2.105263e-02,0.0
C1,-2.552632,-0.057895,0.094737,0.0,0.0,0.0,0.139474,0.155263,0.015789,-0.015789,...,-0.007895,6.973684e-01,0.005263,-0.023684,0.0,0.084211,0.155263,0.065789,2.105263e-02,0.0
C2,-0.447368,0.015789,0.031579,0.0,0.0,0.0,-0.023684,-0.018421,0.005263,-0.005263,...,0.050000,-1.315789e-02,-0.015789,-0.007895,0.0,0.063158,-0.018421,-0.013158,-1.052632e-02,0.0
C3,-2.500000,-0.131579,0.052632,0.0,0.0,0.0,0.092105,0.118421,0.026316,-0.026316,...,-0.013158,9.342105e-01,0.131579,0.065789,0.0,0.052632,0.118421,0.039474,1.168656e-17,0.0
C4,0.052632,0.042105,0.084211,0.0,0.0,0.0,0.068421,0.100000,0.031579,-0.031579,...,-0.015789,1.315789e-01,0.536842,0.005263,0.0,0.221053,0.100000,0.026316,-1.052632e-02,0.0
D1,-0.657895,-0.005263,-0.010526,0.0,0.0,0.0,0.086842,0.102632,0.015789,-0.015789,...,-0.007895,6.578947e-02,0.005263,0.134211,0.0,-0.021053,0.102632,0.118421,1.263158e-01,0.0
D2,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000e+00,0.0
D3,-0.526316,0.042105,-0.126316,0.0,0.0,0.0,0.094737,0.126316,0.031579,-0.031579,...,0.063158,5.263158e-02,0.221053,-0.021053,0.0,1.221053,0.126316,0.052632,4.210526e-02,0.0
D4,-0.342105,0.005263,0.010526,0.0,0.0,0.0,0.202632,0.239474,0.036842,-0.036842,...,-0.018421,1.184211e-01,0.100000,0.102632,0.0,0.126316,0.239474,0.171053,1.368421e-01,0.0
E1,-0.342105,0.026316,0.000000,0.0,0.0,0.0,0.144737,0.171053,0.026316,-0.026316,...,-0.013158,3.947368e-02,0.026316,0.118421,0.0,0.052632,0.171053,0.197368,1.578947e-01,0.0
E2,-0.526316,0.010526,-0.031579,0.0,0.0,0.0,0.115789,0.136842,0.021053,-0.021053,...,-0.010526,1.168656e-17,-0.010526,0.126316,0.0,0.042105,0.136842,0.157895,1.684211e-01,0.0
E3,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000e+00,0.0

刪除列

In [ ]:
qust.drop('A1', axis=1)    #刪除年齡列，axis=1必不可少

,N0.,A2,A3,A4,A5,B1,B2,B3,B4,C1,C2,C3,C4,D1,D2,D3,D4,E1,E2,E3
0,1,1,2,2,1,2,2,1,2,1,2,1,3,2,1,3,2,2,2,1
1,2,1,2,2,1,2,2,1,2,4,2,3,1,2,1,3,2,2,2,1
2,3,2,2,2,1,2,2,1,2,4,2,3,1,2,1,3,2,2,2,1
3,4,2,2,2,1,2,2,1,2,3,2,4,3,2,1,3,2,2,2,1
4,5,1,2,2,1,2,2,1,2,1,2,1,1,2,1,3,2,2,2,1
5,6,2,2,2,1,2,2,1,2,3,2,3,2,2,1,1,2,2,2,1
6,7,1,2,2,1,1,1,1,2,1,2,1,1,2,1,2,1,1,2,1
7,8,2,2,2,1,1,1,1,2,1,2,3,2,2,1,1,1,1,1,1
8,9,2,2,2,1,1,2,2,1,3,2,2,2,2,1,1,2,2,2,1
9,10,2,2,2,1,1,1,1,2,1,2,1,1,2,1,2,1,2,2,1
10,11,1,2,2,1,1,1,1,2,1,2,1,1,2,1,1,1,2,2,1
11,12,2,2,2,1,2,2,1,2,1,2,1,1,2,1,1,2,2,2,1
12,13,2,2,2,1,1,1,1,2,2,2,1,2,1,1,1,1,1,1,1
13,14,2,2,2,1,2,2,1,2,2,2,1,2,2,1,3,2,2,2,1
14,15,1,2,2,1,1,1,1,2,2,2,2,1,1,1,3,1,1,1,1
15,16,2,2,2,1,1,1,1,2,2,2,1,2,1,1,3,1,1,1,1
16,17,1,2,2,1,1,2,2,1,1,2,2,2,2,1,4,2,2,2,1
17,18,2,2,2,1,2,2,1,2,1,2,1,3,2,1,4,2,2,2,1
18,19,1,2,2,1,2,2,1,2,2,1,2,2,2,1,1,2,2,2,1
19,20,2,2,2,1,2,2,1,2,1,2,1,1,2,1,1,2,2,2,1

排序

In [18]:
#bank.sort_values(by=['job','age'])              #根據工作、年齡升序排序
#bank.sort_values(by=['job','age'], ascending=False)     #根據工作、年齡降序排序
#qust.sort_values(by=['D3'])
qust.sort_values(by=['D3'], ascending=False)

,N0.,A1,A2,A3,A4,A5,B1,B2,B3,B4,...,C2,C3,C4,D1,D2,D3,D4,E1,E2,E3
17,18,2,2,2,2,1,2,2,1,2,...,2,1,3,2,1,4,2,2,2,1
16,17,1,1,2,2,1,1,2,2,1,...,2,2,2,2,1,4,2,2,2,1
0,1,1,1,2,2,1,2,2,1,2,...,2,1,3,2,1,3,2,2,2,1
13,14,2,2,2,2,1,2,2,1,2,...,2,1,2,2,1,3,2,2,2,1
2,3,1,2,2,2,1,2,2,1,2,...,2,3,1,2,1,3,2,2,2,1
3,4,1,2,2,2,1,2,2,1,2,...,2,4,3,2,1,3,2,2,2,1
4,5,1,1,2,2,1,2,2,1,2,...,2,1,1,2,1,3,2,2,2,1
1,2,1,1,2,2,1,2,2,1,2,...,2,3,1,2,1,3,2,2,2,1
15,16,2,2,2,2,1,1,1,1,2,...,2,1,2,1,1,3,1,1,1,1
14,15,1,1,2,2,1,1,1,1,2,...,2,2,1,1,1,3,1,1,1,1
6,7,1,1,2,2,1,1,1,1,2,...,2,1,1,2,1,2,1,1,2,1
9,10,2,2,2,2,1,1,1,1,2,...,2,1,1,2,1,2,1,2,2,1
18,19,1,1,2,2,1,2,2,1,2,...,1,2,2,2,1,1,2,2,2,1
10,11,1,1,2,2,1,1,1,1,2,...,2,1,1,2,1,1,1,2,2,1
12,13,1,2,2,2,1,1,1,1,2,...,2,1,2,1,1,1,1,1,1,1
11,12,2,2,2,2,1,2,2,1,2,...,2,1,1,2,1,1,2,2,2,1
8,9,1,2,2,2,1,1,2,2,1,...,2,2,2,2,1,1,2,2,2,1
7,8,1,2,2,2,1,1,1,1,2,...,2,3,2,2,1,1,1,1,1,1
5,6,2,2,2,2,1,2,2,1,2,...,2,3,2,2,1,1,2,2,2,1
19,20,1,2,2,2,1,2,2,1,2,...,2,1,1,2,1,1,2,2,2,1

#多表連線

準備資料：

In [19]:
student = {'Name':['Bob','Alice','Carol','Henry','Judy','Robert','William'],
           'Age':[12,16,13,11,14,15,24],
           'Sex':['M','F','M','M','F','M','F']}

score = {'Name':['Bob','Alice','Carol','Henry','William'],
         'Score':[75,35,87,86,57]}

df_student = pd.DataFrame(student)
df_student

      Name  Age Sex
0      Bob   12   M
1    Alice   16   F
2    Carol   13   M
3    Henry   11   M
4     Judy   14   F
5   Robert   15   M
6  William   24   F

In [ ]:
df_score = pd.DataFrame(score)
df_score

      Name  Score
0      Bob     75
1    Alice     35
2    Carol     87
3    Henry     86
4  William     57

##左連線:

左連線中，沒有Score的學生Score為NaN

In [ ]:
stu_score2 = pd.merge(df_student, df_score, on='Name',how='left')
stu_score2

      Name  Age Sex  Score
0      Bob   12   M   75.0
1    Alice   16   F   35.0
2    Carol   13   M   87.0
3    Henry   11   M   86.0
4     Judy   14   F    NaN
5   Robert   15   M    NaN
6  William   24   F   57.0

#缺失值處理
現實生活中的資料是非常雜亂的，其中缺失值也是非常常見的，對於缺失值的存在可能會影響到後期的資料分析或挖掘工作，那麼我們該如何處理這些缺失值呢？常用的有三大類方法，即刪除法、填補法和插值法。

##1.刪除法
當資料中的某個變數大部分值都是缺失值，可以考慮刪除改變數；當缺失值是隨機分佈的，且缺失的數量並不是很多是，也可以刪除這些缺失的觀測。

##2.替補法
對於連續型變數，如果變數的分佈近似或就是正態分佈的話，可以用均值替代那些缺失值；如果變數是有偏的，可以使用中位數來代替那些缺失值；對於離散型變數，我們一般用眾數去替換那些存在缺失的觀測。

##3.插補法
插補法是基於蒙特卡洛模擬法，結合線性模型、廣義線性模型、決策樹等方法計算出來的預測值替換缺失值。

Ex.以學生成績資料進行處理

查詢某一欄位資料為空的數量

In [ ]:
sum(pd.isnull(stu_score2['Score']))

2

刪除缺失值之前的列表

In [ ]:
stu_score2

      Name  Age Sex  Score
0      Bob   12   M   75.0
1    Alice   16   F   35.0
2    Carol   13   M   87.0
3    Henry   11   M   86.0
4     Judy   14   F    NaN
5   Robert   15   M    NaN
6  William   24   F   57.0

直接刪除缺失值

(預設情況下，dropna會刪除任何含有缺失值的行)

In [ ]:
stu_score2.dropna()

      Name  Age Sex  Score
0      Bob   12   M   75.0
1    Alice   16   F   35.0
2    Carol   13   M   87.0
3    Henry   11   M   86.0
6  William   24   F   57.0

刪除所有行為缺失值的資料

In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame([[1,2,3],[3,4,np.nan],
                  [12,23,43],[55,np.nan,10],
                  [np.nan,np.nan,np.nan],[np.nan,1,2]],
                  columns=['a1','a2','a3'])
df

     a1    a2    a3
0   1.0   2.0   3.0
1   3.0   4.0   NaN
2  12.0  23.0  43.0
3  55.0   NaN  10.0
4   NaN   NaN   NaN
5   NaN   1.0   2.0

In [ ]:
df.dropna()     #該操作會刪除所有有缺失值的行資料

     a1    a2    a3
0   1.0   2.0   3.0
2  12.0  23.0  43.0

In [ ]:
df.dropna(how='all')    #該操作僅會刪除所有列均為缺失值的行資料

     a1    a2    a3
0   1.0   2.0   3.0
1   3.0   4.0   NaN
2  12.0  23.0  43.0
3  55.0   NaN  10.0
5   NaN   1.0   2.0

##填充資料


使用一個常量來填補缺失值，可以使用fillna函式實現簡單的填補工作：

1、用0填補所有缺失值

In [ ]:
df.fillna(0)

     a1    a2    a3
0   1.0   2.0   3.0
1   3.0   4.0   0.0
2  12.0  23.0  43.0
3  55.0   0.0  10.0
4   0.0   0.0   0.0
5   0.0   1.0   2.0

2、採用前項填充或後向填充

In [ ]:
df.fillna(method='ffill')   #用前一個值填充

     a1    a2    a3
0   1.0   2.0   3.0
1   3.0   4.0   3.0
2  12.0  23.0  43.0
3  55.0  23.0  10.0
4  55.0  23.0  10.0
5  55.0   1.0   2.0

In [ ]:
df.fillna(method='bfill')   #用後一個值填充

     a1    a2    a3
0   1.0   2.0   3.0
1   3.0   4.0  43.0
2  12.0  23.0  43.0
3  55.0   1.0  10.0
4   NaN   1.0   2.0
5   NaN   1.0   2.0

3、使用常量填充不同的列

In [ ]:
df.fillna({'a1':100,'a2':200,'a3':300})

      a1     a2     a3
0    1.0    2.0    3.0
1    3.0    4.0  300.0
2   12.0   23.0   43.0
3   55.0  200.0   10.0
4  100.0  200.0  300.0
5  100.0    1.0    2.0

4、用均值或中位數填充各自的列

In [ ]:
a1_median = df['a1'].median()   #計算a1列的中位數
a1_median=7.5

a2_mean = df['a2'].mean()       #計算a2列的均值
a2_mean = 7.5

a3_mean = df['a3'].mean()       #計算a3列的均值
a3_mean = 14.5

df.fillna({'a1':a1_median,'a2':a2_mean,'a3':a3_mean})   #填充值

     a1    a2    a3
0   1.0   2.0   3.0
1   3.0   4.0  14.5
2  12.0  23.0  43.0
3  55.0   7.5  10.0
4   7.5   7.5  14.5
5   7.5   1.0   2.0

在使用填充法時，相對於常數填充或前項、後項填充，使用各列的眾數、均值或中位數填充要更加合理一點，這也是工作中常用的一個快捷手段。

##資料打亂（shuffle）
實際工作中，經常會碰到多個DataFrame合併後希望將資料進行打亂。在pandas中有sample函式可以實現這個操作。

In [ ]:
df = df.sample(frac=1)

這樣對可以對df進行shuffle。其中引數frac是要返回的比例，比如df中有10行資料，我只想返回其中的30%,那麼frac=0.3。

有時候，可能需要打混後資料集的index（索引）還是按照正常的排序。只需要這樣操作:

In [ ]:
df = df.sample(frac=1).reset_index(drop=True)